export module nr.utils:staticUtilsConstants;
import std;

#if !__has_include("staticUtilsConstantsConfig.inl")
#error "staticUtilsConstantsConfig.inl must be generated by CMake before compiling nr.utils."
#else
#include "staticUtilsConstantsConfig.inl"
#endif

#ifndef NR_IS_DEBUG_MODE
#error "NR_IS_DEBUG_MODE must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_MAX_THREADS
#error "NR_MAX_THREADS must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_MAX_FRAME_IN_FLIGHT
#error "NR_MAX_FRAME_IN_FLIGHT must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_STATISTICS_SAMPLE_FRAME_COUNT
#error "NR_STATISTICS_SAMPLE_FRAME_COUNT must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_SHADER_CACHE_ROOT
#error "NR_SHADER_CACHE_ROOT must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_SHADER_ROOT
#error "NR_SHADER_ROOT must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_PROJECT_ROOT
#error "NR_PROJECT_ROOT must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_GLOBAL_LOG_LEVEL
#error "NR_GLOBAL_LOG_LEVEL must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_SHADER_OPTIMIZATION_LEVEL
#error "NR_SHADER_OPTIMIZATION_LEVEL must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_SHADER_DEBUG_INFO_LEVEL
#error "NR_SHADER_DEBUG_INFO_LEVEL must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_SHADER_ENABLE_RICH_DIAGNOSTICS
#error "NR_SHADER_ENABLE_RICH_DIAGNOSTICS must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_SHADER_DUMP_REPRO_ON_ERROR
#error "NR_SHADER_DUMP_REPRO_ON_ERROR must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_SHADER_WARNINGS_AS_ERRORS
#error "NR_SHADER_WARNINGS_AS_ERRORS must be defined by staticUtilsConstantsConfig.inl."
#endif

#ifndef NR_GPU_DEBUG_NAMES_ENABLED
#error "NR_GPU_DEBUG_NAMES_ENABLED must be defined by staticUtilsConstantsConfig.inl."
#endif

export namespace nr
{
inline constexpr bool isDebugMode = NR_IS_DEBUG_MODE;
inline constexpr std::uint32_t maxThreads = NR_MAX_THREADS;
inline constexpr std::uint32_t maxFrameInFlight = NR_MAX_FRAME_IN_FLIGHT;
inline constexpr std::uint32_t statisticsSampleFrameCount = NR_STATISTICS_SAMPLE_FRAME_COUNT;
inline constexpr std::int32_t shaderOptimizationLevel = NR_SHADER_OPTIMIZATION_LEVEL;
inline constexpr std::int32_t shaderDebugInfoLevel = NR_SHADER_DEBUG_INFO_LEVEL;
inline constexpr bool shaderRichDiagnosticsEnabled = NR_SHADER_ENABLE_RICH_DIAGNOSTICS;
inline constexpr bool shaderDumpReproOnError = NR_SHADER_DUMP_REPRO_ON_ERROR;
inline constexpr std::string_view shaderWarningsAsErrors = NR_SHADER_WARNINGS_AS_ERRORS;
inline constexpr bool gpuDebugNamesEnabled = NR_GPU_DEBUG_NAMES_ENABLED;

enum class LogLevel : std::uint32_t
{
    info = 0,
    warning = 1,
    error = 2,
    number = 3
};

inline constexpr LogLevel globalLogLevel = NR_GLOBAL_LOG_LEVEL;

inline constexpr std::array<std::string_view, static_cast<std::size_t>(LogLevel::number)> logLevelNames = {
    "INFO", "WARNING", "ERROR"};

inline constexpr std::string_view projectRoot = NR_PROJECT_ROOT;
inline constexpr std::string_view shaderCacheRoot = NR_SHADER_CACHE_ROOT;
inline constexpr std::string_view shaderRoot = NR_SHADER_ROOT;
} // namespace nr
